### ISSUE TITLE
[Suggestion] State machine example of use

### ISSUE THREAD

**Issue by brucou** [achou11/state-machines#2]
Hi there.

Always happy to see people interested in state machines and promoting the different techniques it enables. Was also happy to see the ressources about user interfaces without VDom.

I wanted to let you know of [Kingly](https://brucou.github.io/documentation/), the state machine library that I maintain. (This could be featured in your [Projects](https://github.com/achou11/state-machines#projects) section.

Also I wrote a lengthy article for [infoQ](https://www.infoq.com/) summarizing all the benefits of state machines and that covers pretty exhaustively the subject, I believe this could be useful in the [Reading](https://github.com/achou11/state-machines#reading) section. The article can also be consulted on Medium: https://medium.com/dailyjs/user-interfaces-you-can-trust-with-state-machines-49de7fa138a6. That is probably the best link to use, as infoQ caters more to senior dev, and software architects.

This is just what I did personally. There are a number of other resources and the subject is vast and not very much dealt with in the front-end world. I may have some ideas as to how to structure the README, I have been thinking a lot of the subject in the last three years. I could make some suggestion in the future if you are open to that. 

On a totally different note, I checked choo.io, which seems like news to me. I used choo (and nanohtml) a long time ago (actually I have a simple [state machine demo](https://codesandbox.io/s/73wy8jwk86 featuring nanomorph). Are you anyhow linked to choo? For some reason, I came to think it was not so much maintained anymore.

Thanks for your consideration. Let me know if you want to include the two links I mentioned previously. I'll be glad to do a PR.

**Comment by achou11** [comment]
Hey @brucou, thanks for creating this! Really cool to see someone whose interest in this has spanned a few years (I'm super new to it, hence this repo).

I believe #1 is going to add Kingly to the list (what a coincidence!). Would love it if you'd create a PR for the links you mentioned, as well as any other appropriate resources that you know about :)

Regarding Choo, I'm just a long-time fan of the ecosystem. Still my favorite framework even though it's not nearly as actively maintained nowadays (it still is though!).

**Comment by brucou** [comment]
Great! I will wait for the other PR to be merged then. That will give me time to think about soome more stuff.

**Comment by brucou** [comment]
@achou11 I finally found the time to submit the PR. Please have a look.

**Comment by brucou** [comment]
found this new one by the way: https://github.com/ericelliott/redux-dsm, quite specialized to a Redux concept, little in the way of documentation, but used in production for some time already, and simple to grasp in the end.
